export default {
  currentLanguage: 'en',
  setCurrentLanguage(language) {
    this.currentLanguage = language;
  },
  getCurrentLanguage() {
    return this.currentLanguage;
  },
};

/* eslint-disable @typescript-eslint/no-unused-vars */
export const trends = ['Mới nhất', 'Đáng chú ý', 'Đang bình luận'];

export const cities = [
  'Nước ngoài',
  'Hà Nội',
  'TP. Hồ Chí Minh',
  'Cần Thơ',
  'Đà Nẵng',
  'Hải Phòng',
  'Đà Lạt',
  'Bắc Ninh',
  'Thái Nguyên',
  'Vinh',
  'Nha Trang',
  'Pleiku',
  'Huế',
  'Hội An',
  'Long Xuyên',
  'Rạch Giá',
  'Hải Dương',
  'Quảng Ninh',
  'Khác',
];

export const provinces = [
  'Nước ngoài',
  'Hà Nội',
  'TP. Hồ Chí Minh',
  'Cần Thơ',
  'Đà Nẵng',
  'Hải Phòng',
  'Bắc Ninh',
  'Đồng Nai',
  'Đắk Lắk',
  'Lâm Đồng',
  'Quảng Ninh',
  'Hải Dương',
  'Huế',
  'An Giang',
  'Tiền Giang',
  'Nam Định',
  'Khánh Hòa',
  'Gia Lai',
  'Bình Định',
  'Thái Nguyên',
  'Thanh Hóa',
  'Bình Dương',
  'Phú Thọ',
  'Nghệ An',
  'Bà Rịa - Vũng Tàu',
  'Bạc Liêu',
  'Bắc Giang',
  'Bến Tre',
  'Cà Mau',
  'Đồng Tháp',
  'Quảng Bình',
  'Hà Tĩnh',
  'Lạng Sơn',
  'Lào Cai',
  'Ninh Bình',
  'Ninh Thuận',
  'Bình Thuận',
  'Kiên Giang',
  'Hà Nam',
  'Quảng Ngãi',
  'Rạch Giá',
  'Sơn La',
  'Quảng Nam',
  'Long An',
  'Thái Bình',
  'Trà Vinh',
  'Phú Yên',
  'Tuyên Quang',
  'Hậu Giang',
  'Vĩnh Long',
  'Vĩnh Phúc',
  'Bắc Kạn',
  'Cao Bằng',
  'Điện Biên',
  'Quảng Trị',
  'Bình Phước',
  'Đắk Nông',
  'Hà Giang',
  'Kiến Giang',
  'Hòa Bình',
  'Hưng Yên',
  'Kon Tum',
  'Lai Châu',
  'Sóc Trăng',
  'Tây Ninh',
  'Yên Bái',
];

export const merchants = [
  'Shopee',
  'Lazada',
  'Tiki',
  'Amazon',
  'eBay',
  'Taobao',
  'AliExpress',
];

export const categories = [
  'Thời trang & phụ kiện',
  'Sức khỏe và làm đẹp',
  'Thiết bị điện tử',
  'TV & Thiết bị điên gia dụng',
  'Nội thất',
  'Thể thao & Du lịch',
  'Thực phẩm',
  'Gói cước điện thoại & Internet',
  'Dịch vụ',
  'Ôtô, xe máy & thiết bị định vị',
];
